### ISSUE TITLE
View egiterakoan informazio gehiegi ageri da

### ISSUE THREAD

**Issue by aortuondo002** [UPV-EHU-Bilbao/algTwitter#7]
bistaratzerakoan ez da argia ( datu gehiegi agertzen dira)
adibidez:[Wed Dec 02 12:14:08 CET 2015]Request: 
[Wed Dec 02 12:14:08 CET 2015]GET https://api.twitter.com/1.1/users/show.json?user_id=1219761840&include_entities=true
[Wed Dec 02 12:14:08 CET 2015]OAuth base string: GET&https%3A%2F%2Fapi.twitter.com%2F1.1%2Fusers%2Fshow.json&include_entities%3Dtrue%26oauth_consumer_key%3D9vj1uaNEO4T6AUQc7OEUw0yOm%26oauth_nonce%3D1079702225%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1449054848%26oauth_token%3D910419368-QkmOSqeFqBH0tL0WA1uDwpi6cLaqlggJekx7Eu9O%26oauth_version%3D1.0%26user_id%3D1219761840
[Wed Dec 02 12:14:08 CET 2015]OAuth signature: XmXYsXovFym+y3ArcqZz0vySQXQ=
[Wed Dec 02 12:14:08 CET 2015]Authorization: *************************************************************************************************************************************************************************************************************************************************************************************
[Wed Dec 02 12:14:08 CET 2015]X-Twitter-Client-Version: 4.0.4
[Wed Dec 02 12:14:08 CET 2015]X-Twitter-Client-URL: http://twitter4j.org/en/twitter4j-4.0.4.xml
[Wed Dec 02 12:14:08 CET 2015]X-Twitter-Client: Twitter4J
[Wed Dec 02 12:14:08 CET 2015]User-Agent: twitter4j http://twitter4j.org/ /4.0.4
[Wed Dec 02 12:14:08 CET 2015]Accept-Encoding: gzip
[Wed Dec 02 12:14:08 CET 2015]Response: 
[Wed Dec 02 12:14:08 CET 2015]date: Wed, 02 Dec 2015 11:14:11 GMT
[Wed Dec 02 12:14:08 CET 2015]HTTP/1.1 200 OK
[Wed Dec 02 12:14:08 CET 2015]server: tsa_f
[Wed Dec 02 12:14:08 CET 2015]content-length: 881
[Wed Dec 02 12:14:08 CET 2015]expires: Tue, 31 Mar 1981 05:00:00 GMT
[Wed Dec 02 12:14:08 CET 2015]x-response-time: 192
[Wed Dec 02 12:14:08 CET 2015]x-frame-options: SAMEORIGIN
[Wed Dec 02 12:14:08 CET 2015]content-encoding: gzip
[Wed Dec 02 12:14:08 CET 2015]x-transaction: 9baddb22452d25a3
[Wed Dec 02 12:14:08 CET 2015]set-cookie: guest_id=v1%3A144905485133182231; Domain=.twitter.com; Path=/; Expires=Fri, 01-Dec-2017 11:14:11 UTC
[Wed Dec 02 12:14:08 CET 2015]set-cookie: lang=es; Path=/
[Wed Dec 02 12:14:08 CET 2015]last-modified: Wed, 02 Dec 2015 11:14:11 GMT
[Wed Dec 02 12:14:08 CET 2015]content-disposition: attachment; filename=json.json
[Wed Dec 02 12:14:08 CET 2015]x-connection-hash: 385db759d35c242d5f7687309e732a40
[Wed Dec 02 12:14:08 CET 2015]x-twitter-response-tags: BouncerCompliant
[Wed Dec 02 12:14:08 CET 2015]content-type: application/json;charset=utf-8
[Wed Dec 02 12:14:08 CET 2015]cache-control: no-cache, no-store, must-revalidate, pre-check=0, post-check=0
[Wed Dec 02 12:14:08 CET 2015]x-rate-limit-reset: 1449055489
[Wed Dec 02 12:14:08 CET 2015]x-rate-limit-remaining: 14
[Wed Dec 02 12:14:08 CET 2015]x-rate-limit-limit: 180
[Wed Dec 02 12:14:08 CET 2015]strict-transport-security: max-age=631138519
[Wed Dec 02 12:14:08 CET 2015]pragma: no-cache
[Wed Dec 02 12:14:08 CET 2015]x-xss-protection: 1; mode=block
[Wed Dec 02 12:14:08 CET 2015]x-content-type-options: nosniff
[Wed Dec 02 12:14:08 CET 2015]x-access-level: read-write-directmessages
[Wed Dec 02 12:14:08 CET 2015]status: 200 OK
[Wed Dec 02 12:14:08 CET 2015]{
 "contributors_enabled": false,
 "created_at": "Mon Feb 25 20:58:25 +0000 2013",
 "default_profile": true,
 "default_profile_image": false,
 "description": "",
 "entities": {"description": {"urls": []}},
 "favourites_count": 0,
 "follow_request_sent": false,
 "followers_count": 6,
 "following": true,
 "friends_count": 21,
 "geo_enabled": true,
 "has_extended_profile": false,
 "id": 1219761840,
 "id_str": "1219761840",
 "is_translation_enabled": false,
 "is_translator": false,
 "lang": "es",
 "listed_count": 0,
 "location": "",
 "name": "irati macias",
 "notifications": false,
 "profile_background_color": "C0DEED",
 "profile_background_image_url": "http://abs.twimg.com/images/themes/theme1/bg.png",
 "profile_background_image_url_https": "https://abs.twimg.com/images/themes/theme1/bg.png",
 "profile_background_tile": false,
 "profile_image_url": "http://pbs.twimg.com/profile_images/3342015900/2cb621f702cac3ce4ab8247186516d29_normal.jpeg",
 "profile_image_url_https": "https://pbs.twimg.com/profile_images/3342015900/2cb621f702cac3ce4ab8247186516d29_normal.jpeg",
 "profile_link_color": "0084B4",
 "profile_location": null,
 "profile_sidebar_border_color": "C0DEED",
 "profile_sidebar_fill_color": "DDEEF6",
 "profile_text_color": "333333",
 "profile_use_background_image": true,
 "protected": false,
 "screen_name": "iratimaci",
 "status": {
  "contributors": null,
  "coordinates": null,
  "created_at": "Sat Sep 07 22:43:25 +0000 2013",
  "entities": {
   "hashtags": [],
   "symbols": [],
   "urls": [],
   "user_mentions": [{
    "id": 577960794,
    "id_str": "577960794",
    "indices": [
     0,
     16
    ],
    "name": "Amaia Rodriguez",
    "screen_name": "AmaiaRodriguez2"
   }]
  },
  "favorite_count": 0,
  "favorited": false,
  "geo": null,
  "id": 376475823341309952,
  "id_str": "376475823341309952",
  "in_reply_to_screen_name": "AmaiaRodriguez2",
  "in_reply_to_status_id": 376474063151300608,
  "in_reply_to_status_id_str": "376474063151300608",
  "in_reply_to_user_id": 577960794,
  "in_reply_to_user_id_str": "577960794",
  "lang": "es",
  "place": null,
  "retweet_count": 0,
  "retweeted": false,
  "source": "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Mobile Web (M5)<\/a>",
  "text": "@AmaiaRodriguez2 golfa pobrexitos los niños estan muy wapos asi",
  "truncated": false
 },
 "statuses_count": 18,
 "time_zone": null,
 "url": null,
 "utc_offset": null,
 "verified": false
}
iratimaci
213523966

Hau tweet bat moduan agertzen da kontsolan

**Comment by galder542** [comment]
ARAZOA KONPONDUTAAAAAAAAAAAA!!!!!!!!!!!!!!
